import {deserialize_binary_filter_data} from './deserializer.mjs';

let b64_example = "RklMVERBVEEAAQAAAAIAAAAPAAAAZGF0YXNldF9saXN0XzEAAgAAAAoAAABkYXRhc2V0XzEABgAAAAYAAAAKAAAAcmFuZ2VfdmFyAAoAAAByYW5nZV92YXIACAAAAGludGVnZXIACgAAAG51bWVyaWNhbAABAAAAAAAAAAAA8D8AAAAAAAAUQAQAAACamZmZmZnZP5qZmZmZmck/mpmZmZmZyT+amZmZmZnJPwkAAABkYXRlX3ZhcgAJAAAAZGF0ZV92YXIABQAAAERhdGUABQAAAGRhdGUAAQAAAAAAAADAQtNAAAAAAMBD00AKAAAAcG9zaXhfdmFyAAoAAABwb3NpeF92YXIACAAAAFBPU0lYY3QABQAAAGRhdGUAAQAAAAAAAADAQtNAAAAAAMBD00ALAAAAc3Vic2V0X3ZhcgALAAAAc3Vic2V0X3ZhcgAHAAAAZmFjdG9yAAwAAABjYXRlZ29yaWNhbAABAAAABQAAAAIAAABhAAIAAABiAAIAAABjAAIAAABkAAIAAABlAAEAAAABAAAAAQAAAAEAAAABAAAADAAAAGxvZ2ljYWxfdmFyAAwAAABsb2dpY2FsX3ZhcgAIAAAAbG9naWNhbAAMAAAAY2F0ZWdvcmljYWwAAQAAAAIAAAAGAAAARkFMU0UABQAAAFRSVUUAAwAAAAIAAAAIAAAAc2JqX3ZhcgAIAAAAc2JqX3ZhcgAKAAAAY2hhcmFjdGVyAAwAAABjYXRlZ29yaWNhbAAAAAAABgAAAAYAAABTQkotMQAGAAAAU0JKLTIABgAAAFNCSi0zAAYAAABTQkotNAAGAAAAU0JKLTUABgAAAFNCSi02AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAoAAABkYXRhc2V0XzIABgAAAAEAAAAIAAAAc2JqX3ZhcgAIAAAAc2JqX3ZhcgAKAAAAY2hhcmFjdGVyAAwAAABjYXRlZ29yaWNhbAAAAAAABgAAAAYAAABTQkotMQAGAAAAU0JKLTIABgAAAFNCSi0zAAYAAABTQkotNAAGAAAAU0JKLTUABgAAAFNCSi02AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAA8AAABkYXRhc2V0X2xpc3RfMgACAAAACgAAAGRhdGFzZXRfMQAGAAAABgAAAAoAAAByYW5nZV92YXIACgAAAHJhbmdlX3ZhcgAIAAAAaW50ZWdlcgAKAAAAbnVtZXJpY2FsAAEAAAAAAAAAAADwPwAAAAAAABRABAAAAJqZmZmZmdk/mpmZmZmZyT+amZmZmZnJP5qZmZmZmck/CQAAAGRhdGVfdmFyAAkAAABkYXRlX3ZhcgAFAAAARGF0ZQAFAAAAZGF0ZQABAAAAAAAAAMBC00AAAAAAwEPTQAoAAABwb3NpeF92YXIACgAAAHBvc2l4X3ZhcgAIAAAAUE9TSVhjdAAFAAAAZGF0ZQABAAAAAAAAAMBC00AAAAAAwEPTQAsAAABzdWJzZXRfdmFyAAsAAABzdWJzZXRfdmFyAAcAAABmYWN0b3IADAAAAGNhdGVnb3JpY2FsAAEAAAAFAAAAAgAAAGEAAgAAAGIAAgAAAGMAAgAAAGQAAgAAAGUAAQAAAAEAAAABAAAAAQAAAAEAAAAMAAAAbG9naWNhbF92YXIADAAAAGxvZ2ljYWxfdmFyAAgAAABsb2dpY2FsAAwAAABjYXRlZ29yaWNhbAABAAAAAgAAAAYAAABGQUxTRQAFAAAAVFJVRQADAAAAAgAAAAgAAABzYmpfdmFyAAgAAABzYmpfdmFyAAoAAABjaGFyYWN0ZXIADAAAAGNhdGVnb3JpY2FsAAAAAAAGAAAABwAAAFNCSi0xMAAHAAAAU0JKLTEyAAYAAABTQkotMgAGAAAAU0JKLTQABgAAAFNCSi02AAYAAABTQkotOAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAKAAAAZGF0YXNldF8yAAYAAAABAAAACAAAAHNial92YXIACAAAAHNial92YXIACgAAAGNoYXJhY3RlcgAMAAAAY2F0ZWdvcmljYWwAAAAAAAYAAAAHAAAAU0JKLTEwAAcAAABTQkotMTIABgAAAFNCSi0yAAYAAABTQkotNAAGAAAAU0JKLTYABgAAAFNCSi04AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAA=="

let deserialized_example = JSON.parse("{\"dataset_lists\":[{\"name\":[\"dataset_list_1\"],\"dataset_list\":[{\"name\":[\"dataset_1\"],\"nrow\":[6],\"variables\":[{\"name\":[\"range_var\"],\"label\":[\"range_var\"],\"class\":[\"integer\"],\"kind\":[\"numerical\"],\"NA_count\":[1],\"min\":[1.0],\"max\":[5.0],\"density\":[0.4,0.2,0.2,0.2]},{\"name\":[\"date_var\"],\"label\":[\"date_var\"],\"class\":[\"Date\"],\"kind\":[\"date\"],\"NA_count\":[1],\"min\":[19723.0],\"max\":[19727.0]},{\"name\":[\"posix_var\"],\"label\":[\"posix_var\"],\"class\":[\"POSIXct\"],\"kind\":[\"date\"],\"NA_count\":[1],\"min\":[19723.0],\"max\":[19727.0]},{\"name\":[\"subset_var\"],\"label\":[\"subset_var\"],\"class\":[\"factor\"],\"kind\":[\"categorical\"],\"NA_count\":[1],\"value\":[\"a\",\"b\",\"c\",\"d\",\"e\"],\"count\":[1,1,1,1,1]},{\"name\":[\"logical_var\"],\"label\":[\"logical_var\"],\"class\":[\"logical\"],\"kind\":[\"categorical\"],\"NA_count\":[1],\"value\":[\"FALSE\",\"TRUE\"],\"count\":[3,2]},{\"name\":[\"sbj_var\"],\"label\":[\"sbj_var\"],\"class\":[\"character\"],\"kind\":[\"categorical\"],\"NA_count\":[0],\"value\":[\"SBJ-1\",\"SBJ-2\",\"SBJ-3\",\"SBJ-4\",\"SBJ-5\",\"SBJ-6\"],\"count\":[1,1,1,1,1,1]}]},{\"name\":[\"dataset_2\"],\"nrow\":[6],\"variables\":[{\"name\":[\"sbj_var\"],\"label\":[\"sbj_var\"],\"class\":[\"character\"],\"kind\":[\"categorical\"],\"NA_count\":[0],\"value\":[\"SBJ-1\",\"SBJ-2\",\"SBJ-3\",\"SBJ-4\",\"SBJ-5\",\"SBJ-6\"],\"count\":[1,1,1,1,1,1]}]}]},{\"name\":[\"dataset_list_2\"],\"dataset_list\":[{\"name\":[\"dataset_1\"],\"nrow\":[6],\"variables\":[{\"name\":[\"range_var\"],\"label\":[\"range_var\"],\"class\":[\"integer\"],\"kind\":[\"numerical\"],\"NA_count\":[1],\"min\":[1.0],\"max\":[5.0],\"density\":[0.4,0.2,0.2,0.2]},{\"name\":[\"date_var\"],\"label\":[\"date_var\"],\"class\":[\"Date\"],\"kind\":[\"date\"],\"NA_count\":[1],\"min\":[19723.0],\"max\":[19727.0]},{\"name\":[\"posix_var\"],\"label\":[\"posix_var\"],\"class\":[\"POSIXct\"],\"kind\":[\"date\"],\"NA_count\":[1],\"min\":[19723.0],\"max\":[19727.0]},{\"name\":[\"subset_var\"],\"label\":[\"subset_var\"],\"class\":[\"factor\"],\"kind\":[\"categorical\"],\"NA_count\":[1],\"value\":[\"a\",\"b\",\"c\",\"d\",\"e\"],\"count\":[1,1,1,1,1]},{\"name\":[\"logical_var\"],\"label\":[\"logical_var\"],\"class\":[\"logical\"],\"kind\":[\"categorical\"],\"NA_count\":[1],\"value\":[\"FALSE\",\"TRUE\"],\"count\":[3,2]},{\"name\":[\"sbj_var\"],\"label\":[\"sbj_var\"],\"class\":[\"character\"],\"kind\":[\"categorical\"],\"NA_count\":[0],\"value\":[\"SBJ-10\",\"SBJ-12\",\"SBJ-2\",\"SBJ-4\",\"SBJ-6\",\"SBJ-8\"],\"count\":[1,1,1,1,1,1]}]},{\"name\":[\"dataset_2\"],\"nrow\":[6],\"variables\":[{\"name\":[\"sbj_var\"],\"label\":[\"sbj_var\"],\"class\":[\"character\"],\"kind\":[\"categorical\"],\"NA_count\":[0],\"value\":[\"SBJ-10\",\"SBJ-12\",\"SBJ-2\",\"SBJ-4\",\"SBJ-6\",\"SBJ-8\"],\"count\":[1,1,1,1,1,1]}]}]}]}");

let buf = Buffer.from(b64_example, "base64");
let deserialized = deserialize_binary_filter_data(buf);

console.log("")

let deser_json = JSON.stringify(deserialized, null, 1);
let deser_json_example = JSON.stringify(deserialized_example, null, 1);

import { writeFileSync } from "fs";

writeFileSync('deser.json', deser_json, 'utf8');
writeFileSync('deser_example.json', deser_json_example, 'utf8');

console.log('File saved successfully!');

console.log("Equal: ", JSON.stringify(deserialized) === JSON.stringify(deserialized_example));

